#:kivy 1.0.9

<LetterBox>:
    size: 100, 100
    canvas:
        Color:
            rgba: self.rgba
        Rectangle:
            pos: self.pos
            size: self.size
        
    Label:
        font_size:50
        font_name:"arial"
        center: self.parent.center
        text: self.parent.underlyingLetter
        color:  0, 0, 0, 1

<RibuardleBoardContainer>:
    RibuardleBoard:
        center: self.parent.center